get http://localhost:8080/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmhhc2thciIsImlhdCI6MTY3MDQzNTg4NCwiZXhwIjoxNjcwNDM5NDg0fQ.JlO0SXN2quhN23OiWaIUmPTpdS29Y0yEJv-bGQ_eL6w