get http://localhost:8080
Content-Type: application/json

###
get http://localhost:8080/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJoYXNrYXIiLCJ1c2VyX2lkIjoxLCJpYXQiOjE2NzA2NzEyODEsImV4cCI6MTY3MDc1NzY4MX0.KuZoqotwtNa92jY3xjpH4qewJU1JtcO5gTiGVGpblmA

###

post http://localhost:8080/register
Content-Type: application/json

{
    "username": "bhaskars",
    "password": "password"
}

###
post http://localhost:8080/generate-token
Content-Type: application/json

{
    "username": "bhaskars",
    "password": "password"
}


###

get http://localhost:8080/api/v1/contact-list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJoYXNrYXJzIiwidXNlcl9pZCI6MSwiaWF0IjoxNjcwNzU2Nzg3LCJleHAiOjE2NzA4NDMxODd9.IiS4eOakmsaeGcItKjg3SMVyj4PMb6eIUD2cI3MxgdA


###
POST http://localhost:8080/api/v1/contact-list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJoYXNrYXIiLCJ1c2VyX2lkIjoxLCJpYXQiOjE2NzA2NzEyODEsImV4cCI6MTY3MDc1NzY4MX0.KuZoqotwtNa92jY3xjpH4qewJU1JtcO5gTiGVGpblmA

{
  "phone": "6378845082",
  "name": "bhaskar"
}

###
POST http://localhost:8080/api/v1/contact-list/bulk
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJoYXNrYXJzIiwidXNlcl9pZCI6MSwiaWF0IjoxNjcwNzU4Mzk0LCJleHAiOjE2NzA4NDQ3OTR9.DSRnE-e1KGEthbBuyRLF35lvMuOAooZBPyEm00poPN8

{
  "contacts_bulk": [{
  "phone": "6378845082",
  "name": "bhaskar"
},
{
  "phone": "6378845082",
  "name": "bhaskar"
}]
}

###
DELETE  http://localhost:8080/api/v1/addressbook
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1rIiwidXNlcl9pZCI6NCwiaWF0IjoxNjcwNjU1NDc3LCJleHAiOjE2NzA3NDE4Nzd9.piuy94ug3hG9Cv-oXdpijFhZxypRbhlQ2BYVcO7E0Iw

{
    "address_id": 0
}